version: "3"
services:
    backend:
        container_name: backend
        image: image_backend
        build: ./backend
        ports:
            - 8000:8000
        env_file:
            - ./backend/.env
